version: "3.8"

services:
  degendrink-hardware:
    build:
      context: ./
      dockerfile: dockerfile
    volumes:
      - /sys/class/gpio/:/sys/class/gpio/:rw
    restart: unless-stopped
    privileged: true